url: http://code4lib.github.io/2016.code4lib.org
permalink: /:categories/:title
exclude: [node_modules]
future: true
timezone: America/New_York
sass:
  load_paths:
    - assets/css
gems:
  - jekyll-bootstrap-sass
bootstrap:
  assets: true